name: 'Label an Issue'
description: 'Labels an issue with user specified text'
inputs:
  github_token:
    description: 'The GitHub token to use for API operation'
  label_text:
    description: 'The text for the label'
    required: true
    default: 'Custom'
outputs:
  issue_author:
    description: 'The username associated with the creation of the issue'
runs:
  using: 'node16'
  main: 'dist/index.js'
